version: '3.9'

services:
  emm_postgres:
    container_name: emm_postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
      LANG: es_ES.UTF-8
      TZ: America/Caracas
    ports:
      - "5432:5432"
    volumes:
      - emm-postgres:/var/lib/postgresql/data

volumes:
  emm-postgres:
    driver: local
